# Generated by Django 4.1.7 on 2023-03-12 20:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0005_alter_projectuser_project"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectuser",
            unique_together={("user", "project")},
        ),
    ]
