# Generated by Django 4.1.7 on 2023-03-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image_url",
            field=models.CharField(
                default="https://images.unsplash.com/photo-1518976024611-28bf4b48222e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fG5vdGVzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=900&q=60",
                max_length=512,
            ),
        ),
    ]
