# Generated by Django 4.1.7 on 2023-03-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_profile_color_alter_project_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="color",
            field=models.CharField(
                choices=[
                    ("red", "red"),
                    ("blue", "blue"),
                    ("green", "green"),
                    ("education", "Education"),
                    ("engineering", "Engineering"),
                    ("finance", "Finance"),
                    ("law", "Law"),
                    ("literature", "Literature"),
                    ("medicine", "Medicine"),
                    ("science", "Science"),
                    ("social_sciences", "Social Sciences"),
                    ("technology", "Technology"),
                ],
                default="red",
                max_length=32,
            ),
        ),
    ]
