# Generated by Django 4.1.7 on 2023-03-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_alter_profile_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="color",
            field=models.CharField(
                choices=[("red", "red"), ("blue", "blue"), ("green", "green")],
                default="red",
                max_length=32,
            ),
        ),
    ]
