# Generated by Django 4.1.7 on 2023-03-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_alter_profile_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="color",
            field=models.CharField(
                choices=[("255,0,0", "red"), ("0,0,255", "blue"), ("0,255,0", "green")],
                default="255,0,0",
                max_length=32,
            ),
        ),
    ]
