# Generated by Django 4.1.7 on 2023-03-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_alter_profile_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="color",
            field=models.CharField(default="#FFFFFF", max_length=9),
        ),
    ]
