# Generated by Django 4.1.7 on 2023-04-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_alter_profile_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectuser",
            name="permission",
            field=models.CharField(
                choices=[
                    ("RWCD", "Read, write, complete and delete"),
                    ("RWC-", "Read, write and complete"),
                    ("RW--", "Read and write"),
                    ("R---", "Read"),
                ],
                default="R---",
                max_length=4,
            ),
        ),
    ]
