# Generated by Django 4.1.7 on 2023-04-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_projectuser_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
