# Generated by Django 4.1.7 on 2023-04-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_project_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
