# Generated by Django 4.1.7 on 2023-04-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0019_alter_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                default="media/images/projects/DEFAULT_PROJECT_IMAGE.jpg",
                upload_to="images/projects/",
            ),
        ),
    ]
