# Generated by Django 4.1.7 on 2023-04-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0021_alter_project_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image_url",
        ),
        migrations.AddField(
            model_name="note",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachment/note/"),
        ),
    ]
