# Generated by Django 4.1.7 on 2023-04-30 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_remove_project_image_url_note_attachment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="attachment",
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="attachment/note/")),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.note"
                    ),
                ),
            ],
        ),
    ]
